kakao:
  feign:
    token_url: https://kauth.kakao.com
    user_url: https://kapi.kakao.com
    req_token: /oauth/token
    req_user: /v2/user/me

  request:
    grant_type: authorization_code
    client_id: ENC(nSHuT06UivSKWOPYZHFZJX3XqZb4PXGR49w0DlLeb8uWlUbSRP240bslBfat/T2G)
    redirect_uri: http://localhost:8080/api/auth/kakao
    client_secret: ENC(FtBWbVxrBZx+uPJNtplfoOfH8qVeOaP8fnqn478fV6EoT4+AMihBMdr77bznFQ+2)


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atwoz?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      port: 6379
      host: localhost
      password:

  flyway:
    enabled: false
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        show_sql: true
