server:
  port: 8080

spring:
  profiles:
    active: local

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${ENCRYPT_KEY}

jwt:
  secret: ENC(dKuMsAUlwfgCHWu65w4ilEEkNY6k9dexaITa5k9S6xj1gr/FujiUZrzx7Gzp0Jeujv/j6GJ36Uw=)
  expiration-period: ENC(Ua9DcFiPKX/5r0/WGkN5JQ==)
