server:
  port: 8080

spring:
  profiles:
    active: local

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${ENCRYPT_KEY}

jwt:
  secret: ENC(UcA03YtOpb+AX2NfSRn2H5TsGwt0QGlMb+9BnCmMfh/+y9gG1INzDPzt36kMWuwJ6jcbnsG4pgFiZpuAciDzS2h5wsvL2NqBb6mXuFWPCjUJ8NEx+xyqt4RcQclXAF98)
  access-token-expired-in: 604800000
  refresh-token-expired-in: 600000