server:
  port: 8080

spring:
  profiles:
    active: local

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${ENCRYPT_KEY}

jwt:
  secret: ENC(UcA03YtOpb+AX2NfSRn2H5TsGwt0QGlMb+9BnCmMfh/+y9gG1INzDPzt36kMWuwJ6jcbnsG4pgFiZpuAciDzS2h5wsvL2NqBb6mXuFWPCjUJ8NEx+xyqt4RcQclXAF98)
#  secret: ENC(t6iKCv1Nj+ygRxG2oZCw3l4v9y0ALS2GfQwYIKvO0tRuPzFp4UYRZYfBFdBW+xQl77rOLbfIPJ13tys/tXj3Qw==)
  expiration-period: ENC(Ua9DcFiPKX/5r0/WGkN5JQ==)